<?php

use Illuminate\Database\Seeder;

class DepartmentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('departments')->insert([
            ['department_name' => 'Ain',                        'department_number' => '01', 'region_id' => '1'],
            ['department_name' => 'Aisne',                      'department_number' => '02', 'region_id' => '7'],
            ['department_name' => 'Allier',                     'department_number' => '03', 'region_id' => '1'],
            ['department_name' => 'Alpes-de-Haute-Provence',    'department_number' => '04', 'region_id' => '13'],
            ['department_name' => 'Hautes-Alpes',               'department_number' => '05', 'region_id' => '13'],
            ['department_name' => 'Alpes-Maritimes',            'department_number' => '06', 'region_id' => '13'],
            ['department_name' => 'Ardèche',                    'department_number' => '07', 'region_id' => '1'],
            ['department_name' => 'Ardennes',                   'department_number' => '08', 'region_id' => '6'],
            ['department_name' => 'Ariège',                     'department_number' => '09', 'region_id' => '11'],
            ['department_name' => 'Aube',                       'department_number' => '10', 'region_id' => '6'],
            ['department_name' => 'Aude',                       'department_number' => '11', 'region_id' => '11'],
            ['department_name' => 'Aveyron',                    'department_number' => '12', 'region_id' => '11'],
            ['department_name' => 'Bouches-du-Rhône',           'department_number' => '13', 'region_id' => '13'],
            ['department_name' => 'Calvados',                   'department_number' => '14', 'region_id' => '9'],
            ['department_name' => 'Cantal',                     'department_number' => '15', 'region_id' => '1'],
            ['department_name' => 'Charente',                   'department_number' => '16', 'region_id' => '10'],
            ['department_name' => 'Charente-Maritime',          'department_number' => '17', 'region_id' => '10'],
            ['department_name' => 'Cher',                       'department_number' => '18', 'region_id' => '4'],
            ['department_name' => 'Corrèze',                    'department_number' => '19', 'region_id' => '10'],
            ['department_name' => 'Corse-du-Sud',               'department_number' => '20', 'region_id' => '5'],
            ['department_name' => 'Haute-Corse',                'department_number' => '20', 'region_id' => '5'],
            ['department_name' => 'Côte-d\'Or',                 'department_number' => '21', 'region_id' => '2'],
            ['department_name' => 'Côte-d\'Armor',              'department_number' => '22', 'region_id' => '3'],
            ['department_name' => 'Creuse',                     'department_number' => '23', 'region_id' => '10'],
            ['department_name' => 'Dordogne',                   'department_number' => '24', 'region_id' => '10'],
            ['department_name' => 'Doubs',                      'department_number' => '25', 'region_id' => '2'],
            ['department_name' => 'Drôme',                      'department_number' => '26', 'region_id' => '1'],
            ['department_name' => 'Doubs',                      'department_number' => '27', 'region_id' => '9'],
            ['department_name' => 'Eure-et-Loir',               'department_number' => '28', 'region_id' => '4'],
            ['department_name' => 'Finistère',                  'department_number' => '29', 'region_id' => '3'],
            ['department_name' => 'Gard',                       'department_number' => '30', 'region_id' => '11'],
            ['department_name' => 'Haute-Garonne',              'department_number' => '31', 'region_id' => '11'],
            ['department_name' => 'Gers',                       'department_number' => '32', 'region_id' => '11'],
            ['department_name' => 'Gironde',                    'department_number' => '33', 'region_id' => '10'],
            ['department_name' => 'Hérault',                    'department_number' => '34', 'region_id' => '11'],
            ['department_name' => 'Ile-et-Vilaine',             'department_number' => '35', 'region_id' => '3'],
            ['department_name' => 'Indre',                      'department_number' => '36', 'region_id' => '4'],
            ['department_name' => 'Indre-et-Loire',             'department_number' => '37', 'region_id' => '4'],
            ['department_name' => 'Isère',                      'department_number' => '38', 'region_id' => '1'],
            ['department_name' => 'Jura',                       'department_number' => '39', 'region_id' => '2'],
            ['department_name' => 'Landes',                     'department_number' => '40', 'region_id' => '10'],
            ['department_name' => 'Loir-et-Cher',               'department_number' => '41', 'region_id' => '4'],
            ['department_name' => 'Loire',                      'department_number' => '42', 'region_id' => '1'],
            ['department_name' => 'Haute-Loire',                'department_number' => '43', 'region_id' => '1'],
            ['department_name' => 'Loire-Atlantique',           'department_number' => '44', 'region_id' => '12'],
            ['department_name' => 'Loiret',                     'department_number' => '45', 'region_id' => '4'],
            ['department_name' => 'Lot',                        'department_number' => '46', 'region_id' => '11'],
            ['department_name' => 'Lot-et-Garonne',             'department_number' => '47', 'region_id' => '10'],
            ['department_name' => 'Lozère',                     'department_number' => '48', 'region_id' => '11'],
            ['department_name' => 'Maine-et-Loire',             'department_number' => '49', 'region_id' => '12'],
            ['department_name' => 'Manche',                     'department_number' => '50', 'region_id' => '9'],
            ['department_name' => 'Marne',                      'department_number' => '51', 'region_id' => '6'],
            ['department_name' => 'Haute-Marne',                'department_number' => '52', 'region_id' => '6'],
            ['department_name' => 'Mayenne',                    'department_number' => '53', 'region_id' => '12'],
            ['department_name' => 'Meurthe-et-Moselle',         'department_number' => '54', 'region_id' => '6'],
            ['department_name' => 'Meuse',                      'department_number' => '55', 'region_id' => '6'],
            ['department_name' => 'Morbihan',                   'department_number' => '56', 'region_id' => '3'],
            ['department_name' => 'Moselle',                    'department_number' => '57', 'region_id' => '6'],
            ['department_name' => 'Nièvre',                     'department_number' => '58', 'region_id' => '2'],
            ['department_name' => 'Nord',                       'department_number' => '59', 'region_id' => '7'],
            ['department_name' => 'Oise',                       'department_number' => '60', 'region_id' => '7'],
            ['department_name' => 'Orne',                       'department_number' => '61', 'region_id' => '9'],
            ['department_name' => 'Pas-de-Calais',              'department_number' => '62', 'region_id' => '7'],
            ['department_name' => 'Puy-de-Dôme',                'department_number' => '63', 'region_id' => '1'],
            ['department_name' => 'Pyrénées-Atlantiques',       'department_number' => '64', 'region_id' => '10'],
            ['department_name' => 'Hautes-Pyrénées',            'department_number' => '65', 'region_id' => '11'],
            ['department_name' => 'Pyrénées-Orientales',        'department_number' => '66', 'region_id' => '11'],
            ['department_name' => 'Bas-Rhin',                   'department_number' => '67', 'region_id' => '6'],
            ['department_name' => 'Haut-Rhin',                  'department_number' => '68', 'region_id' => '6'],
            ['department_name' => 'Rhône',                      'department_number' => '69', 'region_id' => '1'],
            ['department_name' => 'Haute-Saône',                'department_number' => '70', 'region_id' => '2'],
            ['department_name' => 'Saône-et-Loire',             'department_number' => '71', 'region_id' => '2'],
            ['department_name' => 'Sarthe',                     'department_number' => '72', 'region_id' => '12'],
            ['department_name' => 'Savoie',                     'department_number' => '73', 'region_id' => '1'],
            ['department_name' => 'Haute-Savoie',               'department_number' => '74', 'region_id' => '1'],
            ['department_name' => 'Paris',                      'department_number' => '75', 'region_id' => '8'],
            ['department_name' => 'Seine-Maritime',             'department_number' => '76', 'region_id' => '9'],
            ['department_name' => 'Seine-et-Marne',             'department_number' => '77', 'region_id' => '8'],
            ['department_name' => 'Yvelines',                   'department_number' => '78', 'region_id' => '8'],
            ['department_name' => 'Deux-Sèvres',                'department_number' => '79', 'region_id' => '10'],
            ['department_name' => 'Somme',                      'department_number' => '80', 'region_id' => '7'],
            ['department_name' => 'Tarn',                       'department_number' => '81', 'region_id' => '11'],
            ['department_name' => 'Tarn-et-Garonne',            'department_number' => '82', 'region_id' => '11'],
            ['department_name' => 'Var',                        'department_number' => '83', 'region_id' => '13'],
            ['department_name' => 'Vaucluse',                   'department_number' => '84', 'region_id' => '13'],
            ['department_name' => 'Vendée',                     'department_number' => '85', 'region_id' => '12'],
            ['department_name' => 'Vienne',                     'department_number' => '86', 'region_id' => '10'],
            ['department_name' => 'Haute-Vienne',               'department_number' => '87', 'region_id' => '10'],
            ['department_name' => 'Vosges',                     'department_number' => '88', 'region_id' => '6'],
            ['department_name' => 'Yonne',                      'department_number' => '89', 'region_id' => '2'],
            ['department_name' => 'Territoire de Belfort',      'department_number' => '90', 'region_id' => '2'],
            ['department_name' => 'Essonne',                    'department_number' => '91', 'region_id' => '8'],
            ['department_name' => 'Hauts-de-Seine',             'department_number' => '92', 'region_id' => '8'],
            ['department_name' => 'Seine-Saint-Denis',          'department_number' => '93', 'region_id' => '8'],
            ['department_name' => 'Val-de-Marne',               'department_number' => '94', 'region_id' => '8'],
            ['department_name' => 'Val-d\'Oise',                'department_number' => '95', 'region_id' => '8'],
            ['department_name' => 'Guadeloupe',                 'department_number' => '971', 'region_id' => '14'],
            ['department_name' => 'Martinique',                 'department_number' => '972', 'region_id' => '15'],
            ['department_name' => 'Guyane',                     'department_number' => '973', 'region_id' => '16'],
            ['department_name' => 'La Réunion',                 'department_number' => '974', 'region_id' => '17'],
            ['department_name' => 'Mayotte',                    'department_number' => '976', 'region_id' => '18']
        ]);
    }
}
